"""Update review model

Revision ID: 4e9f63eb438a
Revises: 85a5c9d25673
Create Date: 2026-01-31 06:51:43.696633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e9f63eb438a'
down_revision: Union[str, Sequence[str], None] = '85a5c9d25673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('review_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('review', sa.Column('reply_status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_review_review_hash'), 'review', ['review_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_review_hash'), table_name='review')
    op.drop_column('review', 'reply_status_message')
    op.drop_column('review', 'review_hash')
    # ### end Alembic commands ###
