"""Add review model

Revision ID: 85a5c9d25673
Revises: 13f175bd376b
Create Date: 2026-01-30 15:37:15.707596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85a5c9d25673'
down_revision: Union[str, Sequence[str], None] = 'db76f889d0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('guest_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_reply_draft', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('final_reply', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reply_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('rate_plans', 'price_adjustment',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            nullable=False,
    #            existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('rate_plans', 'price_adjustment',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            nullable=True,
    #            existing_server_default=sa.text('0.0'))
    op.drop_table('review')
    # ### end Alembic commands ###
