"""Initial migration

Revision ID: db76f889d0d6
Revises:
Create Date: 2026-01-28 12:33:50.228633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db76f889d0d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addons',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addons_hotel_id'), 'addons', ['hotel_id'], unique=False)
    op.create_table('hotels',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('contact', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_name'), 'hotels', ['name'], unique=False)
    op.create_index(op.f('ix_hotels_slug'), 'hotels', ['slug'], unique=True)
    op.create_table('amenities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenities_hotel_id'), 'amenities', ['hotel_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('last_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_hotel_id'), 'api_keys', ['hotel_id'], unique=False)
    op.create_table('channel_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_logs_hotel_id'), 'channel_logs', ['hotel_id'], unique=False)
    op.create_table('channel_manager_settings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_manager_settings_hotel_id'), 'channel_manager_settings', ['hotel_id'], unique=True)
    op.create_table('competitors',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sa.Enum('BOOKING', 'AGODA', 'EXPEDIA', 'MAKEMYTRIP', 'OTHER', name='competitorsource'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_hotel_id'), 'competitors', ['hotel_id'], unique=False)
    op.create_table('guests',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=False)
    op.create_index(op.f('ix_guests_hotel_id'), 'guests', ['hotel_id'], unique=False)
    op.create_table('integration_settings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('widget_enabled', sa.Boolean(), nullable=False),
    sa.Column('widget_theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('widget_primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('widget_position', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed_domains', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cors_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('webhook_events', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('require_https', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_settings_hotel_id'), 'integration_settings', ['hotel_id'], unique=True)
    op.create_table('promo_codes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discount_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('max_usage', sa.Integer(), nullable=True),
    sa.Column('current_usage', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=False)
    op.create_index(op.f('ix_promo_codes_hotel_id'), 'promo_codes', ['hotel_id'], unique=False)
    op.create_table('rate_plans',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meal_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_adjustment', sa.Float(), nullable=False),
    sa.Column('is_refundable', sa.Boolean(), nullable=False),
    sa.Column('cancellation_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_plans_hotel_id'), 'rate_plans', ['hotel_id'], unique=False)
    op.create_table('room_types',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_occupancy', sa.Integer(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('max_children', sa.Integer(), nullable=False),
    sa.Column('extra_bed_allowed', sa.Boolean(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('total_inventory', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('bed_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('room_size', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_types_hotel_id'), 'room_types', ['hotel_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'STAFF', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_hotel_id'), 'users', ['hotel_id'], unique=False)
    op.create_table('bookings',
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'CHECKED_IN', 'CHECKED_OUT', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('special_requests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('promo_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('DIRECT', 'BOOKING_ENGINE', 'MANUAL', name='bookingsource'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guest_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('booking_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rooms', sa.JSON(), nullable=True),
    sa.Column('addons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.create_index(op.f('ix_bookings_check_in'), 'bookings', ['check_in'], unique=False)
    op.create_index(op.f('ix_bookings_check_out'), 'bookings', ['check_out'], unique=False)
    op.create_index(op.f('ix_bookings_guest_id'), 'bookings', ['guest_id'], unique=False)
    op.create_index(op.f('ix_bookings_hotel_id'), 'bookings', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('channel_room_mappings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_room_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ota_room_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ota_rate_plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['local_room_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_room_mappings_hotel_id'), 'channel_room_mappings', ['hotel_id'], unique=False)
    op.create_table('competitor_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_sold_out', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_rates_check_in_date'), 'competitor_rates', ['check_in_date'], unique=False)
    op.create_index(op.f('ix_competitor_rates_competitor_id'), 'competitor_rates', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_competitor_rates_is_sold_out'), 'competitor_rates', ['is_sold_out'], unique=False)
    op.create_table('room_amenity_links',
    sa.Column('room_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amenity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'amenity_id')
    )
    op.create_table('room_blocks',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_blocks_hotel_id'), 'room_blocks', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_room_blocks_room_type_id'), 'room_blocks', ['room_type_id'], unique=False)
    op.create_table('room_rates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate_plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['rate_plan_id'], ['rate_plans.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_rates_date_from'), 'room_rates', ['date_from'], unique=False)
    op.create_index(op.f('ix_room_rates_date_to'), 'room_rates', ['date_to'], unique=False)
    op.create_index(op.f('ix_room_rates_hotel_id'), 'room_rates', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_room_rates_rate_plan_id'), 'room_rates', ['rate_plan_id'], unique=False)
    op.create_index(op.f('ix_room_rates_room_type_id'), 'room_rates', ['room_type_id'], unique=False)
    op.create_table('user_hotel_links',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'hotel_id')
    )
    op.create_table('payments',
    sa.Column('booking_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'PARTIAL_REFUND', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gateway_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hotel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_hotel_id'), 'payments', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_hotel_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('user_hotel_links')
    op.drop_index(op.f('ix_room_rates_room_type_id'), table_name='room_rates')
    op.drop_index(op.f('ix_room_rates_rate_plan_id'), table_name='room_rates')
    op.drop_index(op.f('ix_room_rates_hotel_id'), table_name='room_rates')
    op.drop_index(op.f('ix_room_rates_date_to'), table_name='room_rates')
    op.drop_index(op.f('ix_room_rates_date_from'), table_name='room_rates')
    op.drop_table('room_rates')
    op.drop_index(op.f('ix_room_blocks_room_type_id'), table_name='room_blocks')
    op.drop_index(op.f('ix_room_blocks_hotel_id'), table_name='room_blocks')
    op.drop_table('room_blocks')
    op.drop_table('room_amenity_links')
    op.drop_index(op.f('ix_competitor_rates_is_sold_out'), table_name='competitor_rates')
    op.drop_index(op.f('ix_competitor_rates_competitor_id'), table_name='competitor_rates')
    op.drop_index(op.f('ix_competitor_rates_check_in_date'), table_name='competitor_rates')
    op.drop_table('competitor_rates')
    op.drop_index(op.f('ix_channel_room_mappings_hotel_id'), table_name='channel_room_mappings')
    op.drop_table('channel_room_mappings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hotel_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guest_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_check_out'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_check_in'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_hotel_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_room_types_hotel_id'), table_name='room_types')
    op.drop_table('room_types')
    op.drop_index(op.f('ix_rate_plans_hotel_id'), table_name='rate_plans')
    op.drop_table('rate_plans')
    op.drop_index(op.f('ix_promo_codes_hotel_id'), table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_integration_settings_hotel_id'), table_name='integration_settings')
    op.drop_table('integration_settings')
    op.drop_index(op.f('ix_guests_hotel_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_competitors_hotel_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_channel_manager_settings_hotel_id'), table_name='channel_manager_settings')
    op.drop_table('channel_manager_settings')
    op.drop_index(op.f('ix_channel_logs_hotel_id'), table_name='channel_logs')
    op.drop_table('channel_logs')
    op.drop_index(op.f('ix_api_keys_hotel_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_amenities_hotel_id'), table_name='amenities')
    op.drop_table('amenities')
    op.drop_index(op.f('ix_hotels_slug'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_name'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_addons_hotel_id'), table_name='addons')
    op.drop_table('addons')
    # ### end Alembic commands ###
